### ISSUE TITLE
Unable to configure External Cloud Cost Configuration (AWS) via UI

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2187]
**Describe the bug**  
When entering details for AWS cloud information in the settings page, you can't get past validation for "Athena Database" and "Athena Tablename".

**To Reproduce**  
1. Go to `/settings`
2. Attempt to configure AWS Cloud integration
3. See errors

**Expected behavior**  
Validation allows you to enter and save values

**Screenshots**  
<img width="535" alt="image" src="https://user-images.githubusercontent.com/43491549/234729456-33d78a85-4364-45b0-b750-9a8e76f5e758.png">

**Please share the support case, if any**  
[ZD Ticket](https://kubecost.zendesk.com/agent/tickets/3954)

**What impact will this have on your ability to get value out of Kubecost?**
The ability to save cloud configuration via UI.

**Comment by kwombach12** [comment]
@keithhand we are going to work on improving our cloud integration in 104. Where are you seeing this though? When I add 'test' in nightly, I dont get these validation errors

**Comment by keithhand** [comment]
@kwombach12 102.2, https://demo.kubecost.xyz/settings. It could be this is fixed in dev 🤷‍♂️

**Comment by kwombach12** [comment]
@jjarrett21 I think you worked on this previously - is there some reason I'm not able to repro in nightly, but facing this issue in xyz? Did we make a change here in 103?

**Comment by jjarrett21** [comment]
I am unsure why but this fix has been in for quite a while I'll do some investigating. @kwombach12

**Comment by kwombach12** [comment]
@jjarrett21 were you able to do any investigating? I am still seeing this in xyz.

cc: @teevans

**Comment by jjarrett21** [comment]
Can you point xyz at the latest rc? @kwombach12

**Comment by kwombach12** [comment]
@jjarrett21 yea when I point xyz at the latest rc, the error persists

**Comment by jjarrett21** [comment]
@kwombach12 i confirmed this change is in develop and 103 not sure what's going on here I'll keep investigating

**Comment by chipzoller** [comment]
No longer an issue. Closing.
